package mappingfiles.sysdb;

/**
 * SysOfflineUserTable generated by MyEclipse Persistence Tools
 */

public class SysOfflineUserTable implements java.io.Serializable {

	// Fields

	private String pkId;
	private String syncTable;
	private String userId;

	// Constructors

	/** default constructor */
	public SysOfflineUserTable() {
	}

	/** full constructor */
	public SysOfflineUserTable(String syncTable, String userId) {
		this.syncTable = syncTable;
		this.userId = userId;
	}

	// Property accessors

	public String getPkId() {
		return this.pkId;
	}

	public void setPkId(String pkId) {
		this.pkId = pkId;
	}

	public String getSyncTable() {
		return this.syncTable;
	}

	public void setSyncTable(String syncTable) {
		this.syncTable = syncTable;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}