package mappingfiles.sysdb;

/**
 * SysOfflineSyncField generated by MyEclipse Persistence Tools
 */

public class SysOfflineSyncField implements java.io.Serializable {

	// Fields

	private String fieldId;
	private String syncTable;
	private String fieldCode;
	private String fieldType;
	private boolean isPk;

	// Constructors

	/** default constructor */
	public SysOfflineSyncField() {
	}

	/** full constructor */
	public SysOfflineSyncField(String syncTable, String fieldCode,
			String fieldType, boolean isPk) {
		this.syncTable = syncTable;
		this.fieldCode = fieldCode;
		this.fieldType = fieldType;
		this.isPk = isPk;
	}

	// Property accessors

	public String getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(String fieldId) {
		this.fieldId = fieldId;
	}

	public String getSyncTable() {
		return this.syncTable;
	}

	public void setSyncTable(String syncTable) {
		this.syncTable = syncTable;
	}

	public String getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(String fieldCode) {
		this.fieldCode = fieldCode;
	}

	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	public boolean getIsPk() {
		return this.isPk;
	}

	public void setIsPk(boolean isPk) {
		this.isPk = isPk;
	}

}