package mappingfiles.sysdb;

/**
 * SysOfflineSyncTable generated by MyEclipse Persistence Tools
 */

public class SysOfflineSyncTable implements java.io.Serializable {

	// Fields

	private String syncId;
	private String sysId;
	private String tableName;
	private String tableCname;
	private String tableSqlFilter;

	// Constructors

	/** default constructor */
	public SysOfflineSyncTable() {
	}

	/** minimal constructor */
	public SysOfflineSyncTable(String sysId, String tableName) {
		this.sysId = sysId;
		this.tableName = tableName;
	}

	/** full constructor */
	public SysOfflineSyncTable(String sysId, String tableName,
			String tableCname, String tableSqlFilter) {
		this.sysId = sysId;
		this.tableName = tableName;
		this.tableCname = tableCname;
		this.tableSqlFilter = tableSqlFilter;
	}

	// Property accessors

	public String getSyncId() {
		return this.syncId;
	}

	public void setSyncId(String syncId) {
		this.syncId = syncId;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getTableCname() {
		return this.tableCname;
	}

	public void setTableCname(String tableCname) {
		this.tableCname = tableCname;
	}

	public String getTableSqlFilter() {
		return this.tableSqlFilter;
	}

	public void setTableSqlFilter(String tableSqlFilter) {
		this.tableSqlFilter = tableSqlFilter;
	}

}