package mappingfiles.sysdb;

/**
 * SysOfflineUpLoadTable generated by MyEclipse Persistence Tools
 */

public class SysOfflineUpLoadTable extends
		mappingfiles.sysdb.SysOfflineSyncTable implements java.io.Serializable {

	// Fields

	// Constructors

	/** default constructor */
	public SysOfflineUpLoadTable() {
	}

	/** minimal constructor */
	public SysOfflineUpLoadTable(String sysId, String tableName) {
		super(sysId, tableName);
	}

	/** full constructor */
	public SysOfflineUpLoadTable(String sysId, String tableName,
			String tableCname, String tableSqlFilter) {
		super(sysId, tableName, tableCname, tableSqlFilter);
	}

	// Property accessors

}