package mappingfiles.sysdb;

/**
 * AbstractSysWfConditionParas generated by MyEclipse - Hibernate Tools
 */

public class SysRulePara implements java.io.Serializable {

	// Fields

	private String paraId;
	private String ruleId;
	private String paraDesc;
	private Long paraType;
	private String paraName;
	private String paraRemark;
	private String paraValuetype;
	private String funParas;
	private Long isShared;
	private String funId;

	// Constructors

	/** default constructor */
	public SysRulePara() {
	}

	public SysRulePara(String paraId) {
		this.paraId = paraId;
	}

	/** minimal constructor */
	public SysRulePara(String paraId, String ruleId) {
		this.paraId = paraId;
		this.ruleId = ruleId;
	}

	/** full constructor */
	public SysRulePara(String paraId, String ruleId, String paraDesc,
			Long paraType, String paraName, String paraRemark,
			String paraValuetype, String funParas, Long isShared, String funId) {
		this.paraId = paraId;
		this.ruleId = ruleId;
		this.paraDesc = paraDesc;
		this.paraType = paraType;
		this.paraName = paraName;
		this.paraRemark = paraRemark;
		this.paraValuetype = paraValuetype;
		this.funParas = funParas;
		this.isShared = isShared;
		this.funId = funId;
	}

	// Property accessors

	public String getParaId() {
		return this.paraId;
	}

	public void setParaId(String paraId) {
		this.paraId = paraId;
	}

	public String getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	public String getParaDesc() {
		return this.paraDesc;
	}

	public void setParaDesc(String paraDesc) {
		this.paraDesc = paraDesc;
	}

	public Long getParaType() {
		return this.paraType;
	}

	public void setParaType(Long paraType) {
		this.paraType = paraType;
	}

	public String getParaName() {
		return this.paraName;
	}

	public void setParaName(String paraName) {
		this.paraName = paraName;
	}

	public String getParaRemark() {
		return this.paraRemark;
	}

	public void setParaRemark(String paraRemark) {
		this.paraRemark = paraRemark;
	}

	public String getParaValuetype() {
		return this.paraValuetype;
	}

	public void setParaValuetype(String paraValuetype) {
		this.paraValuetype = paraValuetype;
	}

	public String getFunParas() {
		return this.funParas;
	}

	public void setFunParas(String funParas) {
		this.funParas = funParas;
	}

	public Long getIsShared() {
		return this.isShared;
	}

	public void setIsShared(Long isShared) {
		this.isShared = isShared;
	}

	public String getFunId() {
		return this.funId;
	}

	public void setFunId(String funId) {
		this.funId = funId;
	}

}