package mappingfiles.sysdb;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractSysRuleFunction generated by MyEclipse - Hibernate Tools
 */

public class SysRuleFunction implements java.io.Serializable {

	// Fields

	private String funId;
	private String funClassname;
	private String funMethod;
	private String funName;
	private String funRemark;
	private String funValuetype;
	private String sysId;
	private Set sysWfFunctionParases = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysRuleFunction() {
	}

	/** full constructor */
	public SysRuleFunction(String funClassname, String funMethod,
			String funName, String funRemark, String funValuetype,
			String sysId, Set sysWfFunctionParases) {
		this.funClassname = funClassname;
		this.funMethod = funMethod;
		this.funName = funName;
		this.funRemark = funRemark;
		this.funValuetype = funValuetype;
		this.sysId = sysId;
		this.sysWfFunctionParases = sysWfFunctionParases;
	}

	// Property accessors

	public String getFunId() {
		return this.funId;
	}

	public void setFunId(String funId) {
		this.funId = funId;
	}

	public String getFunClassname() {
		return this.funClassname;
	}

	public void setFunClassname(String funClassname) {
		this.funClassname = funClassname;
	}

	public String getFunMethod() {
		return this.funMethod;
	}

	public void setFunMethod(String funMethod) {
		this.funMethod = funMethod;
	}

	public String getFunName() {
		return this.funName;
	}

	public void setFunName(String funName) {
		this.funName = funName;
	}

	public String getFunRemark() {
		return this.funRemark;
	}

	public void setFunRemark(String funRemark) {
		this.funRemark = funRemark;
	}

	public String getFunValuetype() {
		return this.funValuetype;
	}

	public void setFunValuetype(String funValuetype) {
		this.funValuetype = funValuetype;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public Set getSysWfFunctionParases() {
		return this.sysWfFunctionParases;
	}

	public void setSysWfFunctionParases(Set sysWfFunctionParases) {
		this.sysWfFunctionParases = sysWfFunctionParases;
	}

}